version: '3.8'

services:
  # Backend API
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: runner
    container_name: dela-api-prod
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=${FRONTEND_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS:-12}
    restart: unless-stopped
    networks:
      - dela-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Web
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      target: runner
    container_name: dela-web-prod
    ports:
      - '3001:3000'
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
      - NEXT_PUBLIC_ENVIRONMENT=production
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - dela-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dela-network:
    driver: bridge
