# ✅ Configuración optimizada para despliegue monorepo
# Base de datos y secretos configurados, listo para producción

[variables]
NODE_ENV = "production"
NIXPACKS_BUILD_CACHE = "1"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "python3", "postgresql"]

[phases.install]
cmds = [
    "npm ci --prefer-offline --no-audit --progress=false --silent",
    "cd api && npx prisma generate"
]

[phases.build]
cmds = [
    "echo '🔄 Generando cliente Prisma para producción...'",
    "cd api && npx prisma generate",
    "echo '🏗️ Construyendo aplicación con Turbo...'",
    "npx turbo run build --filter=api",
    "npx turbo run build --filter=web",
    "echo '✅ Build completado exitosamente'"
]

[phases.deploy]
cmds = [
    "echo '🚀 Aplicando migraciones de base de datos...'",
    "cd api && npx prisma migrate deploy",
    "echo '✅ Base de datos actualizada'"
]

[start]
cmd = "cd api && npm run start:prod"
