# ===========================================
# DOKPLOY CONFIG - BACKEND API ONLY
# ===========================================
# Esta configuración despliega SOLO el backend API
# El frontend se despliega por separado en Vercel

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dela-platform-api
    restart: unless-stopped
    
    # Variables de entorno para producción
    environment:
      NODE_ENV: production
      PORT: 3001
      
      # Base de datos (configurar en Dokploy UI)
      DATABASE_URL: ${DATABASE_URL}
      
      # JWT (configurar en Dokploy UI)
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 24h
      
      # CORS - permitir frontend de Vercel
      FRONTEND_URL: ${FRONTEND_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      
      # Configuración adicional
      BCRYPT_SALT_ROUNDS: 12
      RATE_LIMIT_TTL: 60
      RATE_LIMIT_LIMIT: 100
      LOG_LEVEL: info
    
    ports:
      - "3001:3001"
    
    # Health check para Dokploy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Recursos
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  default:
    name: dela-platform-network
