# Configuración de Dokploy para el Backend (API)
# Solo despliega el backend NestJS + Prisma
services:
  api:
    name: dela-api
    type: nodejs
    environment:
      NODE_ENV: production
      PORT: 3001
      # Variables de base de datos
      DATABASE_URL: $DATABASE_URL
      # Variables JWT
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRES_IN: "7d"
      # CORS
      CORS_ORIGIN: $FRONTEND_URL
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./uploads:/app/uploads
    scaling:
      replicas: 1
      memory: 512MB
      cpu: 0.5
