# Configuración Nixpacks para el Backend
# Optimizada solo para NestJS + Prisma

[start]
cmd = "npm run start:prod"

[build]
cmd = "npm ci --only=production && npm run build"

[setup]
nixpkgs = ["nodejs_18", "openssl"]

[env]
NODE_ENV = "production"
PORT = "3001"

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"
dependsOn = ["install"]

[variables]
NIXPACKS_METADATA = "nodejs"
