# Configuración Nixpacks para el Frontend
# Optimizada para Next.js con Tailwind CSS v4

[start]
cmd = "npm start"

[build]
cmd = "npm ci && npm run build"

[setup]
nixpkgs = ["nodejs_18"]

[env]
NODE_ENV = "production"

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"
dependsOn = ["install"]

[variables]
NIXPACKS_METADATA = "nextjs"

# Configuración específica para evitar problemas con lightningcss
[phases.setup]
nixPkgs = ["nodejs_18", "python3", "gcc", "gnumake"]
